# -*- coding: utf-8 -*-
"""sentimentLabelling_text+mcq_DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G3y14CeBidnLzwF82AWMTvDCn5LpUmHA
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from scipy.sparse import hstack, csr_matrix
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input, Embedding, LSTM, Dense, Dropout, Bidirectional,
    GlobalAveragePooling1D, Attention, Concatenate
)
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam
import warnings
warnings.filterwarnings('ignore')

# Set random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

file_path = '/content/drive/MyDrive/Colab Notebooks/aspect_sentiment_gpu_results.csv'
df = pd.read_csv(file_path)

print(f"\nData Loading:")
print(f"  Total samples: {len(df):,}")
print(f"  Columns: {df.columns.tolist()}")

"""# Data Preparation"""

print("\nData Preparation:")

# Method 1: Select columns properly using a list
selected_columns = ['feedback_text', 'aspect', 'sentiment_roberta']
mcq_columns = [col for col in df.columns if col.startswith('MCQ_')]

# Combine all columns
all_columns = selected_columns + mcq_columns
df = df[all_columns]

# Rename sentiment column
df = df.rename(columns={'sentiment_roberta': 'sentiment'})

# Encode sentiment labels
label_map = {
    'Negative': 0,
    'Neutral': 1,
    'Positive': 2
}

df['sentiment'] = df['sentiment'].map(label_map)

# Drop missing values
df = df.dropna().reset_index(drop=True)

# Create text with aspect conditioning
df['text_with_aspect'] = df['feedback_text'] + " [ASPECT: " + df['aspect'] + "]"

print(f"  Final samples: {len(df):,}")
print("\nClass distribution:")
class_dist = df['sentiment'].value_counts(normalize=True)
for label, prop in class_dist.items():
    label_name = list(label_map.keys())[list(label_map.values()).index(label)]
    print(f"  {label_name}: {prop:.3f}")

"""# MCQ Feature Engineering"""

print("\nMCQ Feature Engineering:")

# Define MCQ to aspect mapping (based on course_type)
# Note: Since each feedback has a course_type, we use course_type-specific mapping
# But for simplicity and generalization, we create features from all MCQ columns

mcq_columns = [col for col in df.columns if col.startswith('MCQ_')]
print(f"  MCQ columns found: {mcq_columns}")

mcq_response_map = {
    'Strongly Disagree': 1,
    'Disagree': 2,
    'Neutral': 3,
    'Agree': 4,
    'Strongly Agree': 5
}

for col in mcq_columns:
    df[col + '_num'] = df[col].map(mcq_response_map)

mcq_feature_cols = []

df['mcq_overall_mean'] = df[[col + '_num' for col in mcq_columns]].mean(axis=1)
mcq_feature_cols.append('mcq_overall_mean')

df['mcq_std'] = df[[col + '_num' for col in mcq_columns]].std(axis=1)
mcq_feature_cols.append('mcq_std')

positive_cols = [col + '_num' for col in mcq_columns]
df['mcq_positive_count'] = (df[positive_cols] >= 4).sum(axis=1)
mcq_feature_cols.append('mcq_positive_count')

df['mcq_negative_count'] = (df[positive_cols] <= 2).sum(axis=1)
mcq_feature_cols.append('mcq_negative_count')

df['mcq_neutral_count'] = (df[positive_cols] == 3).sum(axis=1)
mcq_feature_cols.append('mcq_neutral_count')

print(f"  Created {len(mcq_feature_cols)} MCQ features")
print(f"  Features: {mcq_feature_cols}")

"""# Train Val Test Split"""

print("\nData Splitting:")

X_text = df['text_with_aspect'].values
X_mcq = df[mcq_feature_cols].values
y = df['sentiment'].values

X_text_train, X_text_temp, X_mcq_train, X_mcq_temp, y_train, y_temp = train_test_split(
    X_text, X_mcq, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

X_text_val, X_text_test, X_mcq_val, X_mcq_test, y_val, y_test = train_test_split(
    X_text_temp, X_mcq_temp, y_temp,
    test_size=0.5,
    random_state=42,
    stratify=y_temp
)

print(f"  Train: {len(X_text_train):,}")
print(f"  Validation: {len(X_text_val):,}")
print(f"  Test: {len(X_text_test):,}")

"""# TF-IDF"""

print("\nText Feature Extraction (TF-IDF):")

vectorizer = TfidfVectorizer(max_features=5000)

X_text_train_tfidf = vectorizer.fit_transform(X_text_train)
X_text_val_tfidf = vectorizer.transform(X_text_val)
X_text_test_tfidf = vectorizer.transform(X_text_test)

print(f"  TF-IDF shape: {X_text_train_tfidf.shape}")

"""# MCQ Feature Scaling"""

print("\nMCQ Feature Scaling:")

scaler = StandardScaler()

X_mcq_train_scaled = scaler.fit_transform(X_mcq_train)
X_mcq_val_scaled = scaler.transform(X_mcq_val)
X_mcq_test_scaled = scaler.transform(X_mcq_test)

print(f"  MCQ features shape: {X_mcq_train_scaled.shape}")

"""# Combining Features for ML Models"""

print("\nCombining Features for ML Models:")

X_train_combined = hstack([X_text_train_tfidf, csr_matrix(X_mcq_train_scaled)])
X_val_combined = hstack([X_text_val_tfidf, csr_matrix(X_mcq_val_scaled)])
X_test_combined = hstack([X_text_test_tfidf, csr_matrix(X_mcq_test_scaled)])

print(f"  Combined shape: {X_train_combined.shape}")

"""# Class weights"""

classes = np.unique(y_train)
weights = compute_class_weight('balanced', classes=classes, y=y_train)
class_weights = dict(zip(classes, weights))

print(f"\nClass weights:")
for class_label, weight in class_weights.items():
    label_name = list(label_map.keys())[list(label_map.values()).index(class_label)]
    print(f"  {label_name}: {weight:.3f}")

"""# Eval Func"""

def evaluate_model(y_true, y_pred, model_name, dataset_type="Test"):
    """Unified evaluation function for all models"""

    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, average='macro')
    rec = recall_score(y_true, y_pred, average='macro')
    f1 = f1_score(y_true, y_pred, average='macro')

    print(f"\n{model_name} - {dataset_type} Set:")
    print(f"  Accuracy:  {acc:.4f}")
    print(f"  Precision: {prec:.4f}")
    print(f"  Recall:    {rec:.4f}")
    print(f"  F1-Score:  {f1:.4f}")

    return {'accuracy': acc, 'precision': prec, 'recall': rec, 'f1': f1}

def plot_confusion_matrix(y_true, y_pred, model_name):
    """Plot confusion matrix"""
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Negative', 'Neutral', 'Positive'],
                yticklabels=['Negative', 'Neutral', 'Positive'])
    plt.title(f'Confusion Matrix - {model_name}')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.tight_layout()
    plt.show()

# Store all results
ml_results = []

"""# LOGISTIC REGRESSION (Text + MCQ)"""

print("\n" + "="*60)
print("MODEL 1: LOGISTIC REGRESSION (Text + MCQ)")
print("="*60)

from sklearn.linear_model import LogisticRegression

model_lr = LogisticRegression(max_iter=1000, class_weight=class_weights, random_state=42)
model_lr.fit(X_train_combined, y_train)

y_pred_lr = model_lr.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_lr, "Logistic Regression", "Test")
ml_results.append({**result, 'model': 'Logistic Regression + MCQ'})
plot_confusion_matrix(y_test, y_pred_lr, "Logistic Regression + MCQ")

"""# LINEAR SVM (Text + MCQ)"""

print("\n" + "="*60)
print("MODEL 2: LINEAR SVM (Text + MCQ)")
print("="*60)

from sklearn.svm import LinearSVC

model_svm = LinearSVC(class_weight=class_weights, random_state=42, max_iter=2000)
model_svm.fit(X_train_combined, y_train)

y_pred_svm = model_svm.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_svm, "Linear SVM", "Test")
ml_results.append({**result, 'model': 'Linear SVM + MCQ'})
plot_confusion_matrix(y_test, y_pred_svm, "Linear SVM + MCQ")

"""# RANDOM FOREST (Text + MCQ)"""

print("\n" + "="*60)
print("MODEL 3: RANDOM FOREST (Text + MCQ)")
print("="*60)

from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(
    n_estimators=50,
    max_depth=10,
    class_weight=class_weights,
    n_jobs=-1,
    random_state=42
)
model_rf.fit(X_train_combined, y_train)

y_pred_rf = model_rf.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_rf, "Random Forest", "Test")
ml_results.append({**result, 'model': 'Random Forest + MCQ'})
plot_confusion_matrix(y_test, y_pred_rf, "Random Forest + MCQ")

"""# XGBOOST (Text + MCQ)"""

# MODEL 5: XGBOOST (Fast - No toarray)
print("\n" + "="*60)
print("MODEL 5: XGBOOST")
print("="*60)

from xgboost import XGBClassifier

model_xgb = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    random_state=42,
    n_jobs=-1,
    eval_metric='mlogloss'
)

# Direct fit on sparse matrix - NO toarray()
model_xgb.fit(X_train_combined, y_train)

y_pred_xgb = model_xgb.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_xgb, "XGBoost + MCQ")

ml_results.append(result)
plot_confusion_matrix(y_test, y_pred_xgb, "XGBoost + MCQ")

"""# NAIVE BAYES"""

print("\n" + "="*60)
print("MODEL 2: NAIVE BAYES")
print("="*60)

from sklearn.naive_bayes import MultinomialNB

# Convert to positive values for Naive Bayes
X_train_nb = X_train_combined.copy()
X_train_nb.data = np.abs(X_train_nb.data)

model_nb = MultinomialNB()
model_nb.fit(X_train_nb, y_train)

X_test_nb = X_test_combined.copy()
X_test_nb.data = np.abs(X_test_nb.data)

y_pred_nb = model_nb.predict(X_test_nb)
result = evaluate_model(y_test, y_pred_nb, "Naive Bayes + MCQ")
ml_results.append(result)
plot_confusion_matrix(y_test, y_pred_nb, "Naive Bayes + MCQ")

"""# RIDGE CLASSIFIER"""

print("\n" + "="*60)
print("MODEL 6: RIDGE CLASSIFIER")
print("="*60)

from sklearn.linear_model import RidgeClassifier

model_ridge = RidgeClassifier(random_state=42)
model_ridge.fit(X_train_combined, y_train)

y_pred_ridge = model_ridge.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_ridge, "Ridge Classifier + MCQ")
ml_results.append(result)
plot_confusion_matrix(y_test, y_pred_ridge, "Ridge Classifier + MCQ")

"""# SGD CLASSIFIER"""

print("\n" + "="*60)
print("MODEL 7: SGD CLASSIFIER")
print("="*60)

from sklearn.linear_model import SGDClassifier

model_sgd = SGDClassifier(
    loss='hinge', class_weight=class_weights,
    max_iter=1000, random_state=42, n_jobs=-1
)
model_sgd.fit(X_train_combined, y_train)

y_pred_sgd = model_sgd.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_sgd, "SGD Classifier + MCQ")
ml_results.append(result)
plot_confusion_matrix(y_test, y_pred_sgd, "SGD Classifier + MCQ")

"""# DECISION TREE"""

print("\n" + "="*60)
print("MODEL 8: DECISION TREE")
print("="*60)

from sklearn.tree import DecisionTreeClassifier

model_dt = DecisionTreeClassifier(max_depth=10, class_weight=class_weights, random_state=42)
model_dt.fit(X_train_combined, y_train)

y_pred_dt = model_dt.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_dt, "Decision Tree + MCQ")
ml_results.append(result)
plot_confusion_matrix(y_test, y_pred_dt, "Decision Tree + MCQ")

"""# EXTRA TREES"""

print("\n" + "="*60)
print("MODEL 9: EXTRA TREES")
print("="*60)

from sklearn.ensemble import ExtraTreesClassifier

model_et = ExtraTreesClassifier(
    n_estimators=100, max_depth=10, class_weight=class_weights,
    n_jobs=-1, random_state=42
)
model_et.fit(X_train_combined, y_train)

y_pred_et = model_et.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_et, "Extra Trees + MCQ")
ml_results.append(result)
plot_confusion_matrix(y_test, y_pred_et, "Extra Trees + MCQ")

"""# K-NEAREST NEIGHBOR"""

print("\n" + "="*60)
print("MODEL 10: K-NEAREST NEIGHBORS")
print("="*60)

from sklearn.neighbors import KNeighborsClassifier

# Use dense for KNN
model_knn = KNeighborsClassifier(n_neighbors=5, n_jobs=-1)
model_knn.fit(X_train_dense, y_train)

y_pred_knn = model_knn.predict(X_test_dense)
result = evaluate_model(y_test, y_pred_knn, "KNN + MCQ")
ml_results.append(result)
plot_confusion_matrix(y_test, y_pred_knn, "KNN + MCQ")

"""# Prep for DL"""

print("\n" + "="*60)
print("TOKENIZATION FOR DEEP LEARNING MODELS")
print("="*60)
# Add this to your imports at the top of the file
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
MAX_FEATURES = 5000
MAX_LEN = 100

tokenizer = Tokenizer(num_words=MAX_FEATURES, oov_token='<OOV>')
tokenizer.fit_on_texts(X_text_train)

X_train_seq = tokenizer.texts_to_sequences(X_text_train)
X_val_seq = tokenizer.texts_to_sequences(X_text_val)
X_test_seq = tokenizer.texts_to_sequences(X_text_test)

X_train_pad = pad_sequences(X_train_seq, maxlen=MAX_LEN, padding='post', truncating='post')
X_val_pad = pad_sequences(X_val_seq, maxlen=MAX_LEN, padding='post', truncating='post')
X_test_pad = pad_sequences(X_test_seq, maxlen=MAX_LEN, padding='post', truncating='post')

print(f"  Sequence shape: {X_train_pad.shape}")


def get_callbacks(model_name):
    """Return common callbacks for training"""
    return [
        EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True, verbose=0),
        ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, min_lr=0.00001, verbose=0),
        ModelCheckpoint(f'best_{model_name}.h5', monitor='val_accuracy', save_best_only=True, verbose=0)
    ]

"""# LSTM + MCQ FUSION MODEL"""

# ============================================
# MODEL: LSTM + MCQ FUSION (Matching Text-Only Architecture)
# ============================================

print("\n" + "="*60)
print("MODEL: LSTM + MCQ FUSION")
print("="*60)

# Text input branch - IDENTICAL to Simple LSTM
text_input = Input(shape=(MAX_LEN,), name='text_input')
embedding = Embedding(MAX_FEATURES, 128)(text_input)
lstm = LSTM(64, dropout=0.3, recurrent_dropout=0.3)(embedding)  # No return_sequences, no attention
text_features = lstm  # Direct output from LSTM

# MCQ input branch (additional)
mcq_input = Input(shape=(X_mcq_train_scaled.shape[1],), name='mcq_input')
mcq_dense = Dense(32, activation='relu')(mcq_input)
mcq_dropout = Dropout(0.3)(mcq_dense)

# Combine branches
combined = Concatenate()([text_features, mcq_dropout])

# Dense layers - IDENTICAL to Simple LSTM
dense = Dense(32, activation='relu')(combined)
dropout = Dropout(0.3)(dense)
output = Dense(3, activation='softmax')(dropout)

model_lstm_fusion = Model(inputs=[text_input, mcq_input], outputs=output)
model_lstm_fusion.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model_lstm_fusion.summary()

# Train the model
# Train the model
history_lstm_fusion = model_lstm_fusion.fit(
    [X_train_pad, X_mcq_train_scaled], y_train,
    epochs=20,
    batch_size=64,
    validation_data=([X_val_pad, X_mcq_val_scaled], y_val),
    class_weight=class_weights,
    callbacks=get_callbacks("lstm_fusion"),  # <-- FIXED: call the function
    verbose=1
)
# Evaluate
y_pred_lstm_fusion = model_lstm_fusion.predict([X_test_pad, X_mcq_test_scaled], verbose=0)
y_pred_lstm_fusion = np.argmax(y_pred_lstm_fusion, axis=1)

result = evaluate_model(y_test, y_pred_lstm_fusion, "LSTM + MCQ Fusion")

plot_confusion_matrix(y_test, y_pred_lstm_fusion, "LSTM + MCQ Fusion")

# Plot training history
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].plot(history_lstm_fusion.history['accuracy'], label='Train')
axes[0].plot(history_lstm_fusion.history['val_accuracy'], label='Validation')
axes[0].set_title('LSTM + MCQ Fusion - Accuracy')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Accuracy')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

axes[1].plot(history_lstm_fusion.history['loss'], label='Train')
axes[1].plot(history_lstm_fusion.history['val_loss'], label='Validation')
axes[1].set_title('LSTM + MCQ Fusion - Loss')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Loss')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""# BIDIRECTIONAL LSTM + MCQ FUSION"""

# ============================================
# MODEL: BIDIRECTIONAL LSTM + MCQ FUSION (Matching Text-Only)
# ============================================

print("\n" + "="*60)
print("MODEL: BIDIRECTIONAL LSTM + MCQ FUSION")
print("="*60)

# Text input branch - IDENTICAL to text-only BiLSTM
text_input_bi = Input(shape=(MAX_LEN,), name='text_input_bi')
embedding_bi = Embedding(MAX_FEATURES, 128)(text_input_bi)
bilstm = Bidirectional(LSTM(64, dropout=0.3, recurrent_dropout=0.3))(embedding_bi)
text_features_bi = bilstm  # Direct output, NO extra Dense layer

# MCQ input branch
mcq_input_bi = Input(shape=(X_mcq_train_scaled.shape[1],), name='mcq_input_bi')
mcq_dense_bi = Dense(32, activation='relu')(mcq_input_bi)
mcq_dropout_bi = Dropout(0.3)(mcq_dense_bi)

# Combine branches
combined_bi = Concatenate()([text_features_bi, mcq_dropout_bi])

# Dense layers - IDENTICAL to text-only BiLSTM
dense_bi = Dense(32, activation='relu')(combined_bi)  # Changed from 64 to 32
dropout_bi = Dropout(0.3)(dense_bi)
output_bi = Dense(3, activation='softmax')(dropout_bi)

model_bilstm_fusion = Model(inputs=[text_input_bi, mcq_input_bi], outputs=output_bi)
model_bilstm_fusion.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model_bilstm_fusion.summary()

history_bilstm_fusion = model_bilstm_fusion.fit(
    [X_train_pad, X_mcq_train_scaled], y_train,
    epochs=20, batch_size=64,
    validation_data=([X_val_pad, X_mcq_val_scaled], y_val),
    class_weight=class_weights,
    callbacks=get_callbacks("bilstm_fusion"),  # FIXED
    verbose=1
)

# Evaluate
y_pred_bilstm_fusion = model_bilstm_fusion.predict([X_test_pad, X_mcq_test_scaled], verbose=0)
y_pred_bilstm_fusion = np.argmax(y_pred_bilstm_fusion, axis=1)

result = evaluate_model(y_test, y_pred_bilstm_fusion, "BiLSTM + MCQ Fusion")
plot_confusion_matrix(y_test, y_pred_bilstm_fusion, "BiLSTM + MCQ Fusion")

# Plot training history
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].plot(history_bilstm_fusion.history['accuracy'], label='Train')
axes[0].plot(history_bilstm_fusion.history['val_accuracy'], label='Validation')
axes[0].set_title('BiLSTM + MCQ Fusion - Accuracy')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Accuracy')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

axes[1].plot(history_bilstm_fusion.history['loss'], label='Train')
axes[1].plot(history_bilstm_fusion.history['val_loss'], label='Validation')
axes[1].set_title('BiLSTM + MCQ Fusion - Loss')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Loss')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""# LSTM + ATTENTION + MCQ FUSION"""

# ============================================
# MODEL: LSTM + ATTENTION + MCQ FUSION (Matching Text-Only)
# ============================================

print("\n" + "="*60)
print("MODEL: LSTM + ATTENTION + MCQ FUSION")
print("="*60)

# Text input branch - IDENTICAL to text-only LSTM + Attention
text_input_att = Input(shape=(MAX_LEN,), name='text_input_att')
embedding_att = Embedding(MAX_FEATURES, 128)(text_input_att)
lstm_att = LSTM(64, return_sequences=True, dropout=0.3, recurrent_dropout=0.3)(embedding_att)
attention = Attention()([lstm_att, lstm_att])
text_features_att = GlobalAveragePooling1D()(attention)  # This matches text-only

# MCQ input branch
mcq_input_att = Input(shape=(X_mcq_train_scaled.shape[1],), name='mcq_input_att')
mcq_dense_att = Dense(32, activation='relu')(mcq_input_att)
mcq_dropout_att = Dropout(0.3)(mcq_dense_att)

# Combine branches
combined_att = Concatenate()([text_features_att, mcq_dropout_att])

# Dense layers - IDENTICAL to text-only LSTM + Attention
dense_att = Dense(32, activation='relu')(combined_att)  # Changed from 64 to 32
dropout_att = Dropout(0.3)(dense_att)
output_att = Dense(3, activation='softmax')(dropout_att)

model_attention_fusion = Model(inputs=[text_input_att, mcq_input_att], outputs=output_att)
model_attention_fusion.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model_attention_fusion.summary()

# Train the model
history_attention_fusion = model_attention_fusion.fit(
    [X_train_pad, X_mcq_train_scaled], y_train,
    epochs=20,
    batch_size=64,
    validation_data=([X_val_pad, X_mcq_val_scaled], y_val),
    class_weight=class_weights,
    callbacks=get_callbacks("attention_fusion"),
    verbose=1
)

# Evaluate
y_pred_attention_fusion = model_attention_fusion.predict([X_test_pad, X_mcq_test_scaled], verbose=0)
y_pred_attention_fusion = np.argmax(y_pred_attention_fusion, axis=1)

result = evaluate_model(y_test, y_pred_attention_fusion, "LSTM + Attention + MCQ")
plot_confusion_matrix(y_test, y_pred_attention_fusion, "LSTM + Attention + MCQ")

"""# CNN Text"""

# Add these imports at the top of your file with other Keras imports
from tensorflow.keras.layers import (
    Input, Embedding, LSTM, Dense, Dropout, Bidirectional,
    GlobalAveragePooling1D, GlobalMaxPooling1D, Attention, Concatenate,
    Conv1D, MaxPooling1D  # ← Add these two
)

# ============================================
# MODEL: CNN FOR TEXT + MCQ FUSION (Matching Text-Only)
# ============================================

print("\n" + "="*60)
print("MODEL: CNN FOR TEXT + MCQ FUSION")
print("="*60)

# Text input branch - IDENTICAL to text-only CNN
text_input_cnn = Input(shape=(MAX_LEN,), name='text_input_cnn')
embedding_cnn = Embedding(MAX_FEATURES, 128)(text_input_cnn)
conv1 = Conv1D(128, 5, activation='relu')(embedding_cnn)
pool1 = MaxPooling1D(2)(conv1)
conv2 = Conv1D(64, 3, activation='relu')(pool1)
text_features_cnn = GlobalMaxPooling1D()(conv2)

# MCQ input branch
mcq_input_cnn = Input(shape=(X_mcq_train_scaled.shape[1],), name='mcq_input_cnn')
mcq_dense_cnn = Dense(32, activation='relu')(mcq_input_cnn)
mcq_dropout_cnn = Dropout(0.3)(mcq_dense_cnn)

# Combine branches
combined_cnn = Concatenate()([text_features_cnn, mcq_dropout_cnn])

# Dense layers - IDENTICAL to text-only CNN
dense_cnn = Dense(32, activation='relu')(combined_cnn)  # Changed from 64 to 32
dropout_cnn = Dropout(0.3)(dense_cnn)
output_cnn = Dense(3, activation='softmax')(dropout_cnn)

model_cnn_fusion = Model(inputs=[text_input_cnn, mcq_input_cnn], outputs=output_cnn)
model_cnn_fusion.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model_cnn_fusion.summary()

# Train the model
history_cnn_fusion = model_cnn_fusion.fit(
    [X_train_pad, X_mcq_train_scaled], y_train,
    epochs=20,
    batch_size=64,
    validation_data=([X_val_pad, X_mcq_val_scaled], y_val),
    class_weight=class_weights,
    callbacks=get_callbacks("cnn_fusion"),
    verbose=1
)

# Evaluate
y_pred_cnn_fusion = model_cnn_fusion.predict([X_test_pad, X_mcq_test_scaled], verbose=0)
y_pred_cnn_fusion = np.argmax(y_pred_cnn_fusion, axis=1)

result = evaluate_model(y_test, y_pred_cnn_fusion, "CNN + MCQ Fusion")
plot_confusion_matrix(y_test, y_pred_cnn_fusion, "CNN + MCQ Fusion")

"""# CNN + LSTM HYBRID + MCQ FUSION"""

# ============================================
# MODEL: CNN + LSTM HYBRID + MCQ FUSION (Matching Text-Only)
# ============================================

print("\n" + "="*60)
print("MODEL: CNN + LSTM HYBRID + MCQ FUSION")
print("="*60)

# Text input branch - IDENTICAL to text-only CNN + LSTM
text_input_hybrid = Input(shape=(MAX_LEN,), name='text_input_hybrid')
embedding_hybrid = Embedding(MAX_FEATURES, 128)(text_input_hybrid)
conv_hybrid = Conv1D(64, 3, activation='relu')(embedding_hybrid)
pool_hybrid = MaxPooling1D(2)(conv_hybrid)
lstm_hybrid = LSTM(64, dropout=0.3, recurrent_dropout=0.3)(pool_hybrid)
text_features_hybrid = lstm_hybrid  # REMOVED extra Dense(64) layer

# MCQ input branch
mcq_input_hybrid = Input(shape=(X_mcq_train_scaled.shape[1],), name='mcq_input_hybrid')
mcq_dense_hybrid = Dense(32, activation='relu')(mcq_input_hybrid)
mcq_dropout_hybrid = Dropout(0.3)(mcq_dense_hybrid)

# Combine branches
combined_hybrid = Concatenate()([text_features_hybrid, mcq_dropout_hybrid])

# Dense layers - IDENTICAL to text-only CNN + LSTM
dense_hybrid = Dense(32, activation='relu')(combined_hybrid)  # Changed from 64 to 32
dropout_hybrid = Dropout(0.3)(dense_hybrid)
output_hybrid = Dense(3, activation='softmax')(dropout_hybrid)

model_hybrid_fusion = Model(inputs=[text_input_hybrid, mcq_input_hybrid], outputs=output_hybrid)
model_hybrid_fusion.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model_hybrid_fusion.summary()

# Train the model
history_hybrid_fusion = model_hybrid_fusion.fit(
    [X_train_pad, X_mcq_train_scaled], y_train,
    epochs=20,
    batch_size=64,
    validation_data=([X_val_pad, X_mcq_val_scaled], y_val),
    class_weight=class_weights,
    callbacks=get_callbacks("hybrid_fusion"),
    verbose=1
)

# Evaluate
y_pred_hybrid_fusion = model_hybrid_fusion.predict([X_test_pad, X_mcq_test_scaled], verbose=0)
y_pred_hybrid_fusion = np.argmax(y_pred_hybrid_fusion, axis=1)

result = evaluate_model(y_test, y_pred_hybrid_fusion, "CNN + LSTM + MCQ")
plot_confusion_matrix(y_test, y_pred_hybrid_fusion, "CNN + LSTM + MCQ")

"""# GRU + MCQ FUSION"""

# ============================================
# MODEL: GRU + MCQ FUSION (Matching Text-Only)
# ============================================

print("\n" + "="*60)
print("MODEL: GRU + MCQ FUSION")
print("="*60)

from tensorflow.keras.layers import GRU

# Text input branch - IDENTICAL to text-only GRU
text_input_gru = Input(shape=(MAX_LEN,), name='text_input_gru')
embedding_gru = Embedding(MAX_FEATURES, 128)(text_input_gru)
gru = GRU(64, dropout=0.3, recurrent_dropout=0.3)(embedding_gru)
text_features_gru = gru  # REMOVED extra Dense(64) layer - direct GRU output

# MCQ input branch
mcq_input_gru = Input(shape=(X_mcq_train_scaled.shape[1],), name='mcq_input_gru')
mcq_dense_gru = Dense(32, activation='relu')(mcq_input_gru)
mcq_dropout_gru = Dropout(0.3)(mcq_dense_gru)

# Combine branches
combined_gru = Concatenate()([text_features_gru, mcq_dropout_gru])

# Dense layers - IDENTICAL to text-only GRU
dense_gru = Dense(32, activation='relu')(combined_gru)  # Changed from 64 to 32
dropout_gru = Dropout(0.3)(dense_gru)
output_gru = Dense(3, activation='softmax')(dropout_gru)

model_gru_fusion = Model(inputs=[text_input_gru, mcq_input_gru], outputs=output_gru)
model_gru_fusion.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model_gru_fusion.summary()

# Train the model
history_gru_fusion = model_gru_fusion.fit(
    [X_train_pad, X_mcq_train_scaled], y_train,
    epochs=20,
    batch_size=64,
    validation_data=([X_val_pad, X_mcq_val_scaled], y_val),
    class_weight=class_weights,
    callbacks=get_callbacks("gru_fusion"),
    verbose=1
)

# Evaluate
y_pred_gru_fusion = model_gru_fusion.predict([X_test_pad, X_mcq_test_scaled], verbose=0)
y_pred_gru_fusion = np.argmax(y_pred_gru_fusion, axis=1)

result = evaluate_model(y_test, y_pred_gru_fusion, "GRU + MCQ Fusion")
plot_confusion_matrix(y_test, y_pred_gru_fusion, "GRU + MCQ Fusion")

"""# Comparison"""

# ============================================
# 18. FINAL COMPARISON TABLE (ALL MODELS)
# ============================================

print("\n" + "="*70)
print("FINAL COMPARISON: ALL TEXT + MCQ FUSION MODELS")
print("="*70)

# Combine ML and DL results
all_fusion_results = ml_results + dl_results
comparison_df = pd.DataFrame(all_fusion_results)
comparison_df = comparison_df.sort_values('f1', ascending=False).reset_index(drop=True)
comparison_df.index = comparison_df.index + 1

print(comparison_df.to_string())

print(f"\nBest Text+MCQ Model: {comparison_df.iloc[0]['model']}")
print(f"  F1-Score: {comparison_df.iloc[0]['f1']:.4f}")

# Save results
comparison_df.to_csv('text_mcq_all_fusion_results.csv', index=False)
print("\nSaved: text_mcq_all_fusion_results.csv")

# ============================================
# 19. VISUAL COMPARISON
# ============================================

fig, ax = plt.subplots(figsize=(12, 8))

models = comparison_df['model'].tolist()
f1_scores = comparison_df['f1'].tolist()

# Color coding: Green for best, Blue for others
colors = ['#2ecc71' if i == 0 else '#3498db' for i in range(len(models))]

bars = ax.barh(range(len(models)), f1_scores, color=colors)
ax.set_yticks(range(len(models)))
ax.set_yticklabels(models, fontsize=9)
ax.set_xlabel('Macro F1-Score')
ax.set_title('Text + MCQ Fusion Models Comparison (All 16 Models)')
ax.invert_yaxis()

for i, (bar, score) in enumerate(zip(bars, f1_scores)):
    ax.text(bar.get_width() + 0.005, bar.get_y() + bar.get_height()/2,
            f'{score:.4f}', va='center', fontsize=9)

plt.tight_layout()
plt.savefig('text_mcq_fusion_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

print("Saved: text_mcq_fusion_comparison.png")

tf.keras.backend.clear_session()