# -*- coding: utf-8 -*-
"""sentimentLabelling_text+mcq_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b95nG3JICNFO8sL08-gxTTTQzIk-nWI2
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from scipy.sparse import hstack, csr_matrix
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input, Embedding, LSTM, Dense, Dropout, Bidirectional,
    GlobalAveragePooling1D, Attention, Concatenate
)
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam
import warnings
warnings.filterwarnings('ignore')

# Set random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

file_path = '/content/drive/MyDrive/aspect_sentiment_gpu_results.csv'
df = pd.read_csv(file_path)

print(f"\nData Loading:")
print(f"  Total samples: {len(df):,}")
print(f"  Columns: {df.columns.tolist()}")

"""# Data Preparation"""

print("\nData Preparation:")

# Method 1: Select columns properly using a list
selected_columns = ['feedback_text', 'aspect', 'sentiment_roberta']
mcq_columns = [col for col in df.columns if col.startswith('MCQ_')]

# Combine all columns
all_columns = selected_columns + mcq_columns
df = df[all_columns]

# Rename sentiment column
df = df.rename(columns={'sentiment_roberta': 'sentiment'})

# Encode sentiment labels
label_map = {
    'Negative': 0,
    'Neutral': 1,
    'Positive': 2
}

df['sentiment'] = df['sentiment'].map(label_map)

# Drop missing values
df = df.dropna().reset_index(drop=True)

# Create text with aspect conditioning
df['text_with_aspect'] = df['feedback_text'] + " [ASPECT: " + df['aspect'] + "]"

print(f"  Final samples: {len(df):,}")
print("\nClass distribution:")
class_dist = df['sentiment'].value_counts(normalize=True)
for label, prop in class_dist.items():
    label_name = list(label_map.keys())[list(label_map.values()).index(label)]
    print(f"  {label_name}: {prop:.3f}")

"""# MCQ Feature Engineering"""

print("\nMCQ Feature Engineering:")

# Define MCQ to aspect mapping (based on course_type)
# Note: Since each feedback has a course_type, we use course_type-specific mapping
# But for simplicity and generalization, we create features from all MCQ columns

mcq_columns = [col for col in df.columns if col.startswith('MCQ_')]
print(f"  MCQ columns found: {mcq_columns}")

mcq_response_map = {
    'Strongly Disagree': 1,
    'Disagree': 2,
    'Neutral': 3,
    'Agree': 4,
    'Strongly Agree': 5
}

for col in mcq_columns:
    df[col + '_num'] = df[col].map(mcq_response_map)

mcq_feature_cols = []

df['mcq_overall_mean'] = df[[col + '_num' for col in mcq_columns]].mean(axis=1)
mcq_feature_cols.append('mcq_overall_mean')

df['mcq_std'] = df[[col + '_num' for col in mcq_columns]].std(axis=1)
mcq_feature_cols.append('mcq_std')

positive_cols = [col + '_num' for col in mcq_columns]
df['mcq_positive_count'] = (df[positive_cols] >= 4).sum(axis=1)
mcq_feature_cols.append('mcq_positive_count')

df['mcq_negative_count'] = (df[positive_cols] <= 2).sum(axis=1)
mcq_feature_cols.append('mcq_negative_count')

df['mcq_neutral_count'] = (df[positive_cols] == 3).sum(axis=1)
mcq_feature_cols.append('mcq_neutral_count')

print(f"  Created {len(mcq_feature_cols)} MCQ features")
print(f"  Features: {mcq_feature_cols}")

"""# Train Val Test Split"""

print("\nData Splitting:")

X_text = df['text_with_aspect'].values
X_mcq = df[mcq_feature_cols].values
y = df['sentiment'].values

X_text_train, X_text_temp, X_mcq_train, X_mcq_temp, y_train, y_temp = train_test_split(
    X_text, X_mcq, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

X_text_val, X_text_test, X_mcq_val, X_mcq_test, y_val, y_test = train_test_split(
    X_text_temp, X_mcq_temp, y_temp,
    test_size=0.5,
    random_state=42,
    stratify=y_temp
)

print(f"  Train: {len(X_text_train):,}")
print(f"  Validation: {len(X_text_val):,}")
print(f"  Test: {len(X_text_test):,}")

"""# TF-IDF"""

print("\nText Feature Extraction (TF-IDF):")

vectorizer = TfidfVectorizer(max_features=5000)

X_text_train_tfidf = vectorizer.fit_transform(X_text_train)
X_text_val_tfidf = vectorizer.transform(X_text_val)
X_text_test_tfidf = vectorizer.transform(X_text_test)

print(f"  TF-IDF shape: {X_text_train_tfidf.shape}")

"""# MCQ Feature Scaling"""

print("\nMCQ Feature Scaling:")

scaler = StandardScaler()

X_mcq_train_scaled = scaler.fit_transform(X_mcq_train)
X_mcq_val_scaled = scaler.transform(X_mcq_val)
X_mcq_test_scaled = scaler.transform(X_mcq_test)

print(f"  MCQ features shape: {X_mcq_train_scaled.shape}")

"""# Combining Features for ML Models"""

print("\nCombining Features for ML Models:")

X_train_combined = hstack([X_text_train_tfidf, csr_matrix(X_mcq_train_scaled)])
X_val_combined = hstack([X_text_val_tfidf, csr_matrix(X_mcq_val_scaled)])
X_test_combined = hstack([X_text_test_tfidf, csr_matrix(X_mcq_test_scaled)])

print(f"  Combined shape: {X_train_combined.shape}")

"""# Class weights"""

classes = np.unique(y_train)
weights = compute_class_weight('balanced', classes=classes, y=y_train)
class_weights = dict(zip(classes, weights))

print(f"\nClass weights:")
for class_label, weight in class_weights.items():
    label_name = list(label_map.keys())[list(label_map.values()).index(class_label)]
    print(f"  {label_name}: {weight:.3f}")

"""# Eval Func"""

def evaluate_model(y_true, y_pred, model_name, dataset_type="Test"):
    """Unified evaluation function for all models"""

    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, average='macro')
    rec = recall_score(y_true, y_pred, average='macro')
    f1 = f1_score(y_true, y_pred, average='macro')

    print(f"\n{model_name} - {dataset_type} Set:")
    print(f"  Accuracy:  {acc:.4f}")
    print(f"  Precision: {prec:.4f}")
    print(f"  Recall:    {rec:.4f}")
    print(f"  F1-Score:  {f1:.4f}")

    return {'accuracy': acc, 'precision': prec, 'recall': rec, 'f1': f1}

def plot_confusion_matrix(y_true, y_pred, model_name):
    """Plot confusion matrix"""
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Negative', 'Neutral', 'Positive'],
                yticklabels=['Negative', 'Neutral', 'Positive'])
    plt.title(f'Confusion Matrix - {model_name}')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.tight_layout()
    plt.show()

# Store all results
ml_results = []

"""# LOGISTIC REGRESSION (Text + MCQ)"""

print("\n" + "="*60)
print("MODEL 1: LOGISTIC REGRESSION (Text + MCQ)")
print("="*60)

from sklearn.linear_model import LogisticRegression

model_lr = LogisticRegression(max_iter=1000, class_weight=class_weights, random_state=42)
model_lr.fit(X_train_combined, y_train)

y_pred_lr = model_lr.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_lr, "Logistic Regression", "Test")
ml_results.append({**result, 'model': 'Logistic Regression + MCQ'})
plot_confusion_matrix(y_test, y_pred_lr, "Logistic Regression + MCQ")

"""# LINEAR SVM (Text + MCQ)"""

print("\n" + "="*60)
print("MODEL 2: LINEAR SVM (Text + MCQ)")
print("="*60)

from sklearn.svm import LinearSVC

model_svm = LinearSVC(class_weight=class_weights, random_state=42, max_iter=2000)
model_svm.fit(X_train_combined, y_train)

y_pred_svm = model_svm.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_svm, "Linear SVM", "Test")
ml_results.append({**result, 'model': 'Linear SVM + MCQ'})
plot_confusion_matrix(y_test, y_pred_svm, "Linear SVM + MCQ")

"""# RANDOM FOREST (Text + MCQ)"""

print("\n" + "="*60)
print("MODEL 3: RANDOM FOREST (Text + MCQ)")
print("="*60)

from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(
    n_estimators=50,
    max_depth=10,
    class_weight=class_weights,
    n_jobs=-1,
    random_state=42
)
model_rf.fit(X_train_combined, y_train)

y_pred_rf = model_rf.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_rf, "Random Forest", "Test")
ml_results.append({**result, 'model': 'Random Forest + MCQ'})
plot_confusion_matrix(y_test, y_pred_rf, "Random Forest + MCQ")

"""# XGBOOST (Text + MCQ)"""

# MODEL 5: XGBOOST (Fast - No toarray)
print("\n" + "="*60)
print("MODEL 5: XGBOOST")
print("="*60)

from xgboost import XGBClassifier

model_xgb = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    random_state=42,
    n_jobs=-1,
    eval_metric='mlogloss'
)

# Direct fit on sparse matrix - NO toarray()
model_xgb.fit(X_train_combined, y_train)

y_pred_xgb = model_xgb.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_xgb, "XGBoost + MCQ")

ml_results.append(result)
plot_confusion_matrix(y_test, y_pred_xgb, "XGBoost + MCQ")

"""# NAIVE BAYES"""

print("\n" + "="*60)
print("MODEL 2: NAIVE BAYES")
print("="*60)

from sklearn.naive_bayes import MultinomialNB

# Convert to positive values for Naive Bayes
X_train_nb = X_train_combined.copy()
X_train_nb.data = np.abs(X_train_nb.data)

model_nb = MultinomialNB()
model_nb.fit(X_train_nb, y_train)

X_test_nb = X_test_combined.copy()
X_test_nb.data = np.abs(X_test_nb.data)

y_pred_nb = model_nb.predict(X_test_nb)
result = evaluate_model(y_test, y_pred_nb, "Naive Bayes + MCQ")
ml_results.append(result)
plot_confusion_matrix(y_test, y_pred_nb, "Naive Bayes + MCQ")

"""# RIDGE CLASSIFIER"""

print("\n" + "="*60)
print("MODEL 6: RIDGE CLASSIFIER")
print("="*60)

from sklearn.linear_model import RidgeClassifier

model_ridge = RidgeClassifier(random_state=42)
model_ridge.fit(X_train_combined, y_train)

y_pred_ridge = model_ridge.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_ridge, "Ridge Classifier + MCQ")
ml_results.append(result)
plot_confusion_matrix(y_test, y_pred_ridge, "Ridge Classifier + MCQ")

"""# SGD CLASSIFIER"""

print("\n" + "="*60)
print("MODEL 7: SGD CLASSIFIER")
print("="*60)

from sklearn.linear_model import SGDClassifier

model_sgd = SGDClassifier(
    loss='hinge', class_weight=class_weights,
    max_iter=1000, random_state=42, n_jobs=-1
)
model_sgd.fit(X_train_combined, y_train)

y_pred_sgd = model_sgd.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_sgd, "SGD Classifier + MCQ")
ml_results.append(result)
plot_confusion_matrix(y_test, y_pred_sgd, "SGD Classifier + MCQ")

"""# DECISION TREE"""

print("\n" + "="*60)
print("MODEL 8: DECISION TREE")
print("="*60)

from sklearn.tree import DecisionTreeClassifier

model_dt = DecisionTreeClassifier(max_depth=10, class_weight=class_weights, random_state=42)
model_dt.fit(X_train_combined, y_train)

y_pred_dt = model_dt.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_dt, "Decision Tree + MCQ")
ml_results.append(result)
plot_confusion_matrix(y_test, y_pred_dt, "Decision Tree + MCQ")

"""# EXTRA TREES"""

print("\n" + "="*60)
print("MODEL 9: EXTRA TREES")
print("="*60)

from sklearn.ensemble import ExtraTreesClassifier

model_et = ExtraTreesClassifier(
    n_estimators=100, max_depth=10, class_weight=class_weights,
    n_jobs=-1, random_state=42
)
model_et.fit(X_train_combined, y_train)

y_pred_et = model_et.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_et, "Extra Trees + MCQ")
ml_results.append(result)
plot_confusion_matrix(y_test, y_pred_et, "Extra Trees + MCQ")

"""# lgbm"""

# ============================================
# LIGHTGBM (Text + MCQ)
# ============================================

print("\n" + "="*60)
print("MODEL: LIGHTGBM (Text + MCQ)")
print("="*60)

from lightgbm import LGBMClassifier

model_lgb = LGBMClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    class_weight='balanced',  # Use balanced class weights
    random_state=42,
    n_jobs=-1,
    verbose=-1  # Suppress training messages
)

# Train on combined features (TF-IDF + MCQ)
model_lgb.fit(X_train_combined, y_train)

# Predict and evaluate
y_pred_lgb = model_lgb.predict(X_test_combined)
result = evaluate_model(y_test, y_pred_lgb, "LightGBM + MCQ", "Test")

# Store results
ml_results.append({**result, 'model': 'LightGBM + MCQ'})

# Plot confusion matrix
plot_confusion_matrix(y_test, y_pred_lgb, "LightGBM + MCQ")

"""# cross val"""

# ============================================
# CROSS-VALIDATION FOR TEXT+MCQ MODELS
# ============================================

from sklearn.model_selection import cross_val_score, StratifiedKFold

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

cv_results = []

# Use X_train_combined (NOT X_train)
models = [
    ("Linear SVM", model_svm),
    ("Logistic Regression", model_lr),
    ("XGBoost", model_xgb),
    ("LightGBM", model_lgb),
    ("SGD Classifier", model_sgd),
    ("Ridge Classifier", model_ridge),
    ("Random Forest", model_rf),
    ("Extra Trees", model_et),
    ("Naive Bayes", model_nb),
    ("Decision Tree", model_dt)
]

print("="*60)
print("5-FOLD CROSS-VALIDATION RESULTS (Text+MCQ)")
print("="*60)

for name, model in models:
    # Cross-validation doesn't retrain from scratch - it creates temporary copies
    cv_scores = cross_val_score(model, X_train_combined, y_train, cv=cv, scoring='f1_macro', n_jobs=-1)

    cv_results.append({
        'Model': name,
        'CV Mean F1': f"{cv_scores.mean():.4f}",
        'CV Std': f"{cv_scores.std():.4f}",
        'CV Range': f"{cv_scores.min():.4f} - {cv_scores.max():.4f}"
    })

    print(f"\n{name}:")
    print(f"  CV F1 Scores: {cv_scores}")
    print(f"  Mean F1: {cv_scores.mean():.4f} (±{cv_scores.std():.4f})")

# Create comparison DataFrame
cv_df = pd.DataFrame(cv_results)
cv_df = cv_df.sort_values('CV Mean F1', ascending=False)

print("\n" + "="*60)
print("CROSS-VALIDATION RANKING (by Mean F1) - Text+MCQ")
print("="*60)
print(cv_df.to_string(index=False))

# Save results
cv_df.to_csv('text_mcq_cv_results.csv', index=False)
print("\nSaved: text_mcq_cv_results.csv")

"""# K-NEAREST NEIGHBOR"""

# ============================================
# CREATE DENSE MATRICES FOR KNN (Do this BEFORE KNN model)
# ============================================

print("\nCreating dense matrices for KNN...")
X_train_dense = X_train_combined.toarray()
X_test_dense = X_test_combined.toarray()
print(f"  X_train_dense shape: {X_train_dense.shape}")
print(f"  X_test_dense shape: {X_test_dense.shape}")

# ============================================
# MODEL 10: K-NEAREST NEIGHBORS
# ============================================

print("\n" + "="*60)
print("MODEL 10: K-NEAREST NEIGHBORS")
print("="*60)

from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier(n_neighbors=5, n_jobs=-1)
model_knn.fit(X_train_dense, y_train)

y_pred_knn = model_knn.predict(X_test_dense)
result = evaluate_model(y_test, y_pred_knn, "KNN + MCQ")
ml_results.append({**result, 'model': 'KNN + MCQ'})
plot_confusion_matrix(y_test, y_pred_knn, "KNN + MCQ")

# ============================================
# KNN CROSS-VALIDATION (Separate from other models)
# ============================================

from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
import pandas as pd

print("="*60)
print("KNN 5-FOLD CROSS-VALIDATION")
print("="*60)

# Create dense matrix once
print("\nCreating dense matrix for KNN CV...")
X_train_dense = X_train_combined.toarray()
print(f"  X_train_dense shape: {X_train_dense.shape}")
print(f"  Memory: {X_train_dense.nbytes / 1024**3:.2f} GB")

# Setup cross-validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# KNN model
knn_cv_model = KNeighborsClassifier(n_neighbors=5, n_jobs=-1)

# Perform cross-validation
print("\nRunning 5-fold cross-validation...")
knn_cv_scores = cross_val_score(knn_cv_model, X_train_dense, y_train,
                                 cv=cv, scoring='f1_macro', n_jobs=-1)

# Display results
print(f"\nK-Nearest Neighbors CV Results:")
print(f"  CV F1 Scores: {knn_cv_scores}")
print(f"  Mean F1: {knn_cv_scores.mean():.4f} (±{knn_cv_scores.std():.4f})")
print(f"  Range: {knn_cv_scores.min():.4f} - {knn_cv_scores.max():.4f}")

# Store results
knn_cv_result = {
    'Model': 'K-Nearest Neighbors',
    'CV Mean F1': f"{knn_cv_scores.mean():.4f}",
    'CV Std': f"{knn_cv_scores.std():.4f}",
    'CV Range': f"{knn_cv_scores.min():.4f} - {knn_cv_scores.max():.4f}"
}

# Save to CSV
knn_cv_df = pd.DataFrame([knn_cv_result])
knn_cv_df.to_csv('knn_cv_results.csv', index=False)
print("\nSaved: knn_cv_results.csv")