# -*- coding: utf-8 -*-
"""SentimentLabelling-text only -DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VAikUc-rNgJceDF6L1OscbXKTq0HxcV8
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.utils.class_weight import compute_class_weight
import tensorflow as tf
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import (
    Input, Embedding, LSTM, Dense, Dropout, Bidirectional,
    GlobalAveragePooling1D, GlobalMaxPooling1D, Attention,
    Conv1D, MaxPooling1D
)
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.optimizers import Adam
import warnings
warnings.filterwarnings('ignore')

# Set random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

import tensorflow as tf

print("TensorFlow version:", tf.__version__)
print("GPU Available:", tf.config.list_physical_devices('GPU'))

if tf.config.list_physical_devices('GPU'):
    print("GPU Device:", tf.config.experimental.get_device_details(tf.config.list_physical_devices('GPU')[0]))
else:
    print("WARNING: No GPU detected. Training will be very slow.")

"""# Load Data"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

file_path = '/content/drive/MyDrive/Colab Notebooks/aspect_sentiment_gpu_results.csv'
df = pd.read_csv(file_path)

"""# Data Preparation"""

print("\nData Loading:")
print(f"  Total samples: {len(df):,}")
print(f"  Columns: {df.columns.tolist()}")

print("\nData Preparation:")

df = df[['feedback_text', 'aspect', 'sentiment_roberta']]
df = df.rename(columns={'sentiment_roberta': 'sentiment'})

label_map = {
    'Negative': 0,
    'Neutral': 1,
    'Positive': 2
}

df['sentiment'] = df['sentiment'].map(label_map)

df = df.dropna().reset_index(drop=True)

# Create model input with aspect conditioning
df['model_input'] = df['feedback_text'] + " [ASPECT: " + df['aspect'] + "]"

print(f"  Final samples: {len(df):,}")
print("\nClass distribution:")
class_dist = df['sentiment'].value_counts(normalize=True)
for label, prop in class_dist.items():
    label_name = list(label_map.keys())[list(label_map.values()).index(label)]
    print(f"  {label_name}: {prop:.3f}")

print("\nData Splitting:")

train_df, temp_df = train_test_split(df, test_size=0.3, random_state=42)
val_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42)

print(f"  Train: {len(train_df):,}")
print(f"  Validation: {len(val_df):,}")
print(f"  Test: {len(test_df):,}")

MAX_FEATURES = 5000
MAX_LEN = 100

print(f"\nTokenization:")
print(f"  Max features: {MAX_FEATURES}")
print(f"  Max sequence length: {MAX_LEN}")

tokenizer = Tokenizer(num_words=MAX_FEATURES, oov_token='<OOV>')
tokenizer.fit_on_texts(train_df['model_input'])

X_train_seq = tokenizer.texts_to_sequences(train_df['model_input'])
X_val_seq = tokenizer.texts_to_sequences(val_df['model_input'])
X_test_seq = tokenizer.texts_to_sequences(test_df['model_input'])

X_train_pad = pad_sequences(X_train_seq, maxlen=MAX_LEN, padding='post', truncating='post')
X_val_pad = pad_sequences(X_val_seq, maxlen=MAX_LEN, padding='post', truncating='post')
X_test_pad = pad_sequences(X_test_seq, maxlen=MAX_LEN, padding='post', truncating='post')

y_train = train_df['sentiment'].values
y_val = val_df['sentiment'].values
y_test = test_df['sentiment'].values

print(f"\nPadded shapes:")
print(f"  X_train: {X_train_pad.shape}")
print(f"  X_val: {X_val_pad.shape}")
print(f"  X_test: {X_test_pad.shape}")

"""# Class Balancing"""

classes = np.unique(y_train)
weights = compute_class_weight('balanced', classes=classes, y=y_train)
class_weights = dict(zip(classes, weights))

print(f"\nClass weights:")
for class_label, weight in class_weights.items():
    label_name = list(label_map.keys())[list(label_map.values()).index(class_label)]
    print(f"  {label_name}: {weight:.3f}")

"""# Eval Report"""

def evaluate_model(model, X_test, y_test, model_name, history=None):
    """Unified evaluation function for deep learning models"""

    y_pred_proba = model.predict(X_test, verbose=0)
    y_pred = np.argmax(y_pred_proba, axis=1)

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='macro')
    rec = recall_score(y_test, y_pred, average='macro')
    f1 = f1_score(y_test, y_pred, average='macro')

    print(f"\n{'='*50}")
    print(f"{model_name}")
    print(f"{'='*50}")
    print(f"Accuracy:  {acc:.4f}")
    print(f"Precision: {prec:.4f}")
    print(f"Recall:    {rec:.4f}")
    print(f"F1-Score:  {f1:.4f}")

    print(f"\nPer-Class Performance:")
    print(classification_report(y_test, y_pred,
                                target_names=['Negative', 'Neutral', 'Positive']))

    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Negative', 'Neutral', 'Positive'],
                yticklabels=['Negative', 'Neutral', 'Positive'])
    plt.title(f'Confusion Matrix - {model_name}')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.tight_layout()
    plt.show()

    if history is not None:
        fig, axes = plt.subplots(1, 2, figsize=(12, 4))

        axes[0].plot(history.history['accuracy'], label='Train')
        axes[0].plot(history.history['val_accuracy'], label='Validation')
        axes[0].set_title(f'{model_name} - Accuracy')
        axes[0].set_xlabel('Epoch')
        axes[0].set_ylabel('Accuracy')
        axes[0].legend()
        axes[0].grid(True, alpha=0.3)

        axes[1].plot(history.history['loss'], label='Train')
        axes[1].plot(history.history['val_loss'], label='Validation')
        axes[1].set_title(f'{model_name} - Loss')
        axes[1].set_xlabel('Epoch')
        axes[1].set_ylabel('Loss')
        axes[1].legend()
        axes[1].grid(True, alpha=0.3)

        plt.tight_layout()
        plt.show()

    return {
        'model': model_name,
        'accuracy': acc,
        'precision': prec,
        'recall': rec,
        'f1': f1
    }

def get_callbacks(model_name):
    """Return common callbacks for training"""
    return [
        EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True, verbose=0),
        ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, min_lr=0.00001, verbose=0),
        ModelCheckpoint(f'best_{model_name}.h5', monitor='val_accuracy', save_best_only=True, verbose=0)
    ]

dl_results = []

"""# LSTM"""

print("\n" + "="*60)
print("MODEL 1: SIMPLE LSTM")
print("="*60)

def build_simple_lstm():
    model = Sequential([
        Embedding(MAX_FEATURES, 128, input_length=MAX_LEN),
        LSTM(64, dropout=0.3, recurrent_dropout=0.3),
        Dense(32, activation='relu'),
        Dropout(0.3),
        Dense(3, activation='softmax')
    ])
    model.compile(optimizer=Adam(learning_rate=0.001),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

model_lstm = build_simple_lstm()
model_lstm.summary()

history_lstm = model_lstm.fit(
    X_train_pad, y_train,
    epochs=20,
    batch_size=64,
    validation_data=(X_val_pad, y_val),
    class_weight=class_weights,
    callbacks=get_callbacks('simple_lstm'),
    verbose=1
)

result = evaluate_model(model_lstm, X_test_pad, y_test, "Simple LSTM", history_lstm)
dl_results.append(result)

"""# Bi-LSTM"""

print("\n" + "="*60)
print("MODEL 2: BIDIRECTIONAL LSTM")
print("="*60)

def build_bilstm():
    model = Sequential([
        Embedding(MAX_FEATURES, 128, input_length=MAX_LEN),
        Bidirectional(LSTM(64, dropout=0.3, recurrent_dropout=0.3)),
        Dense(32, activation='relu'),
        Dropout(0.3),
        Dense(3, activation='softmax')
    ])
    model.compile(optimizer=Adam(learning_rate=0.001),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

model_bilstm = build_bilstm()
model_bilstm.summary()

history_bilstm = model_bilstm.fit(
    X_train_pad, y_train,
    epochs=20,
    batch_size=64,
    validation_data=(X_val_pad, y_val),
    class_weight=class_weights,
    callbacks=get_callbacks('bilstm'),
    verbose=1
)

result = evaluate_model(model_bilstm, X_test_pad, y_test, "Bidirectional LSTM", history_bilstm)
dl_results.append(result)

"""# LSTM -Attention"""

print("\n" + "="*60)
print("MODEL 3: LSTM WITH ATTENTION")
print("="*60)

def build_lstm_attention():
    inputs = Input(shape=(MAX_LEN,))
    embedding = Embedding(MAX_FEATURES, 128)(inputs)

    lstm = LSTM(64, return_sequences=True, dropout=0.3, recurrent_dropout=0.3)(embedding)
    attention = Attention()([lstm, lstm])
    pool = GlobalAveragePooling1D()(attention)

    dense = Dense(32, activation='relu')(pool)
    dropout = Dropout(0.3)(dense)
    outputs = Dense(3, activation='softmax')(dropout)

    model = Model(inputs=inputs, outputs=outputs)
    model.compile(optimizer=Adam(learning_rate=0.001),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

model_lstm_attn = build_lstm_attention()
model_lstm_attn.summary()

history_lstm_attn = model_lstm_attn.fit(
    X_train_pad, y_train,
    epochs=20,
    batch_size=64,
    validation_data=(X_val_pad, y_val),
    class_weight=class_weights,
    callbacks=get_callbacks('lstm_attention'),
    verbose=1
)

result = evaluate_model(model_lstm_attn, X_test_pad, y_test, "LSTM + Attention", history_lstm_attn)
dl_results.append(result)

"""# CNN - Text"""

print("\n" + "="*60)
print("MODEL 4: CNN FOR TEXT")
print("="*60)

def build_cnn_text():
    model = Sequential([
        Embedding(MAX_FEATURES, 128, input_length=MAX_LEN),
        Conv1D(128, 5, activation='relu'),
        MaxPooling1D(2),
        Conv1D(64, 3, activation='relu'),
        GlobalMaxPooling1D(),
        Dense(32, activation='relu'),
        Dropout(0.3),
        Dense(3, activation='softmax')
    ])
    model.compile(optimizer=Adam(learning_rate=0.001),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

model_cnn = build_cnn_text()
model_cnn.summary()

history_cnn = model_cnn.fit(
    X_train_pad, y_train,
    epochs=20,
    batch_size=64,
    validation_data=(X_val_pad, y_val),
    class_weight=class_weights,
    callbacks=get_callbacks('cnn'),
    verbose=1
)

result = evaluate_model(model_cnn, X_test_pad, y_test, "CNN for Text", history_cnn)
dl_results.append(result)

"""# CNN-LSTM"""

print("\n" + "="*60)
print("MODEL 5: CNN + LSTM HYBRID")
print("="*60)

def build_cnn_lstm():
    model = Sequential([
        Embedding(MAX_FEATURES, 128, input_length=MAX_LEN),
        Conv1D(64, 3, activation='relu'),
        MaxPooling1D(2),
        LSTM(64, dropout=0.3, recurrent_dropout=0.3),
        Dense(32, activation='relu'),
        Dropout(0.3),
        Dense(3, activation='softmax')
    ])
    model.compile(optimizer=Adam(learning_rate=0.001),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

model_cnn_lstm = build_cnn_lstm()
model_cnn_lstm.summary()

history_cnn_lstm = model_cnn_lstm.fit(
    X_train_pad, y_train,
    epochs=20,
    batch_size=64,
    validation_data=(X_val_pad, y_val),
    class_weight=class_weights,
    callbacks=get_callbacks('cnn_lstm'),
    verbose=1
)

result = evaluate_model(model_cnn_lstm, X_test_pad, y_test, "CNN + LSTM", history_cnn_lstm)
dl_results.append(result)

"""# GRU"""

print("\n" + "="*60)
print("MODEL 6: GRU")
print("="*60)

from tensorflow.keras.layers import GRU

def build_gru():
    model = Sequential([
        Embedding(MAX_FEATURES, 128, input_length=MAX_LEN),
        GRU(64, dropout=0.3, recurrent_dropout=0.3),
        Dense(32, activation='relu'),
        Dropout(0.3),
        Dense(3, activation='softmax')
    ])
    model.compile(optimizer=Adam(learning_rate=0.001),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

model_gru = build_gru()
model_gru.summary()

history_gru = model_gru.fit(
    X_train_pad, y_train,
    epochs=20,
    batch_size=64,
    validation_data=(X_val_pad, y_val),
    class_weight=class_weights,
    callbacks=get_callbacks('gru'),
    verbose=1
)

result = evaluate_model(model_gru, X_test_pad, y_test, "GRU", history_gru)
dl_results.append(result)

"""# Comparion, Visualization"""

print("\n" + "="*70)
print("DEEP LEARNING MODELS - FINAL COMPARISON")
print("="*70)

comparison_df = pd.DataFrame(dl_results)
comparison_df = comparison_df.sort_values('f1', ascending=False).reset_index(drop=True)
comparison_df.index = comparison_df.index + 1

print(comparison_df.to_string())

print(f"\nBest Deep Learning Model: {comparison_df.iloc[0]['model']}")
print(f"  Accuracy: {comparison_df.iloc[0]['accuracy']:.4f}")
print(f"  F1-Score: {comparison_df.iloc[0]['f1']:.4f}")

# Save results
comparison_df.to_csv('dl_model_comparison.csv', index=False)
print("\nSaved: dl_model_comparison.csv")

fig, ax = plt.subplots(figsize=(10, 6))

models = comparison_df['model'].tolist()
f1_scores = comparison_df['f1'].tolist()
colors = ['#2ecc71' if i == 0 else '#3498db' for i in range(len(models))]

bars = ax.barh(range(len(models)), f1_scores, color=colors)
ax.set_yticks(range(len(models)))
ax.set_yticklabels(models)
ax.set_xlabel('Macro F1-Score')
ax.set_title('Deep Learning Models Comparison')
ax.invert_yaxis()

for i, (bar, score) in enumerate(zip(bars, f1_scores)):
    ax.text(bar.get_width() + 0.005, bar.get_y() + bar.get_height()/2,
            f'{score:.4f}', va='center', fontsize=9)

plt.tight_layout()
plt.savefig('dl_model_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

print("\nSaved: dl_model_comparison.png")

tf.keras.backend.clear_session()